spring.application.name=SteamProject

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/steamstats
spring.datasource.username=postgres
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

steam.app.ids=730,570,1172470
spring.config.import=optional:file:../.env.properties


